import org.springframework.cloud.openfeign.encoding.FeignContentGzipEncodingAutoConfiguration;
public class FunctionUse154 {
public void funcUse() {
FeignContentGzipEncodingAutoConfiguration feigncontentgzipencodingautoconfiguration = new FeignContentGzipEncodingAutoConfiguration();
feigncontentgzipencodingautoconfiguration.feignContentGzipEncodingInterceptor(null);
}
}